In [282]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as mplt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_curve
import seaborn as sns
import urllib.request as urllib2
import pickle

In [283]:
data  = pd.read_csv('bdata.csv')

In [284]:
data['URL_Length'] = list(map(len, data['Domain']))

In [285]:
data['Have_IP']

0       0
1       0
2       0
3       0
4       0
       ..
9995    0
9996    0
9997    0
9998    0
9999    0
Name: Have_IP, Length: 10000, dtype: int64

In [449]:
data

,Domain,Have_IP,Have_At,URL_Length,URL_Depth,Redirection,https_Domain,TinyURL,Prefix/Suffix,DNS_Record,Web_Traffic,Domain_Age,Domain_End,iFrame,Mouse_Over,Right_Click,Web_Forwards,Label
0,graphicriver.net,0,0,16,1,0,0,0,0,0,1,1,1,0,0,1,0,0
1,ecnavi.jp,0,0,9,1,1,0,0,0,0,1,1,1,0,0,1,0,0
2,hubpages.com,0,0,12,1,0,0,0,0,0,1,0,1,0,0,1,0,0
3,extratorrent.cc,0,0,15,3,0,0,0,0,0,1,0,1,0,0,1,0,0
4,icicibank.com,0,0,13,3,0,0,0,0,0,1,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,wvk12-my.sharepoint.com,0,0,23,5,0,0,1,1,0,1,1,1,0,0,1,0,1
9996,adplife.com,0,0,11,4,0,0,0,0,0,1,0,1,0,0,1,0,1
9997,kurortnoye.com.ua,0,1,17,3,0,0,1,0,0,0,1,1,1,0,1,0,1
9998,norcaltc-my.sharepoint.com,0,0,26,5,0,0,1,1,0,1,1,1,0,0,1,0,1
9999,sieck-kuehlsysteme.de,0,1,21,4,0,0,1,1,0,1,1,1,0,0,1,0,1

In [287]:
#Dropping the Domain column
vdata = data.drop(['Domain'], axis = 1)

In [288]:
vdata = vdata.drop(['Redirection'], axis = 1)
vdata = vdata.drop(['Domain_End'], axis = 1)

In [289]:
vdata

,Have_IP,Have_At,URL_Length,URL_Depth,https_Domain,TinyURL,Prefix/Suffix,DNS_Record,Web_Traffic,Domain_Age,iFrame,Mouse_Over,Right_Click,Web_Forwards,Label
0,0,0,16,1,0,0,0,0,1,1,0,0,1,0,0
1,0,0,9,1,0,0,0,0,1,1,0,0,1,0,0
2,0,0,12,1,0,0,0,0,1,0,0,0,1,0,0
3,0,0,15,3,0,0,0,0,1,0,0,0,1,0,0
4,0,0,13,3,0,0,0,0,1,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0,0,23,5,0,1,1,0,1,1,0,0,1,0,1
9996,0,0,11,4,0,0,0,0,1,0,0,0,1,0,1
9997,0,1,17,3,0,1,0,0,0,1,1,0,1,0,1
9998,0,0,26,5,0,1,1,0,1,1,0,0,1,0,1
9999,0,1,21,4,0,1,1,0,1,1,0,0,1,0,1

In [290]:
vdata = vdata.sample(frac=1).reset_index(drop=True)

In [291]:
vdata

,Have_IP,Have_At,URL_Length,URL_Depth,https_Domain,TinyURL,Prefix/Suffix,DNS_Record,Web_Traffic,Domain_Age,iFrame,Mouse_Over,Right_Click,Web_Forwards,Label
0,0,0,11,1,0,0,0,0,1,1,0,0,1,0,0
1,0,0,78,1,0,0,1,1,1,1,0,0,1,0,1
2,0,0,12,2,0,0,0,0,0,1,0,0,1,0,0
3,0,0,13,2,0,0,0,1,1,1,0,0,1,0,0
4,0,0,11,4,0,0,0,0,0,0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0,0,19,6,0,0,0,0,1,1,0,0,1,0,0
9996,0,0,23,1,0,0,0,0,1,0,0,0,1,0,1
9997,0,0,32,5,0,1,1,0,0,1,0,0,1,0,1
9998,0,0,20,3,0,1,0,0,1,1,0,0,1,0,1
9999,0,0,11,4,0,0,0,0,1,1,0,0,1,0,0

In [292]:
y = vdata['Label']

In [293]:
x = vdata.drop('Label', axis='columns')

In [294]:
train_X, test_X, train_Y, test_Y = train_test_split(x, y, test_size=0.25)

In [295]:
train_Y.shape

(7500,)

In [455]:
forest = RandomForestClassifier(n_estimators=300)

In [456]:
forest.fit(train_X, train_Y)

RandomForestClassifier(n_estimators=300)

In [457]:
test_X

,Have_IP,Have_At,URL_Length,URL_Depth,https_Domain,TinyURL,Prefix/Suffix,DNS_Record,Web_Traffic,Domain_Age,iFrame,Mouse_Over,Right_Click,Web_Forwards
8443,0,0,26,0,0,0,0,0,1,0,0,0,1,0
7323,0,0,10,2,0,0,0,0,1,0,0,0,1,0
2967,0,1,22,3,0,1,0,1,1,1,0,0,1,0
5623,0,0,19,5,0,0,0,0,0,0,0,0,1,0
3815,0,0,43,0,0,0,1,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6502,0,0,14,2,0,0,0,0,1,1,0,0,1,0
7191,0,0,12,1,0,0,0,0,1,0,0,0,1,0
3238,0,0,11,1,0,0,0,0,1,1,0,0,1,0
3507,0,0,14,8,0,0,0,0,1,0,0,0,1,0
9098,0,0,8,1,0,0,0,0,0,0,0,0,1,0

In [458]:
forest.predict(test_X)

array([1, 0, 1, ..., 0, 1, 1])

In [459]:
accuracy_score(test_Y,forest.predict(test_X))

0.8904

In [301]:
from urllib.parse import urlparse, urlencode
import ipaddress
import re

In [302]:
def get_domain(url):  
    domain = urlparse(url).netloc
    if domain[:4] == 'www.':
        domain = domain[4:]
    return domain

In [303]:
def if_ip(url):
    try:
        ipaddress.ip_address(url)
        ip = 1
    except:
        ip = 0
    return ip

In [304]:
def at_sign(url):
    if "@" in url:
        if_at = 1    
    else:
        if_at = 0    
    return if_at

In [305]:
def get_length(url):
    return len(url)

In [306]:
def get_depth(url):
    return url.count('/')

In [307]:
def if_https_in_domain(url):
    domain = urlparse(url).netloc
    if 'https' in domain:
        return 1
    else:
        return 0

In [308]:
shortening_services = r"bit\.ly|goo\.gl|shorte\.st|go2l\.ink|x\.co|ow\.ly|t\.co|tinyurl|tr\.im|is\.gd|cli\.gs|" \
                      r"yfrog\.com|migre\.me|ff\.im|tiny\.cc|url4\.eu|twit\.ac|su\.pr|twurl\.nl|snipurl\.com|" \
                      r"short\.to|BudURL\.com|ping\.fm|post\.ly|Just\.as|bkite\.com|snipr\.com|fic\.kr|loopt\.us|" \
                      r"doiop\.com|short\.ie|kl\.am|wp\.me|rubyurl\.com|om\.ly|to\.ly|bit\.do|t\.co|lnkd\.in|db\.tt|" \
                      r"qr\.ae|adf\.ly|goo\.gl|bitly\.com|cur\.lv|tinyurl\.com|ow\.ly|bit\.ly|ity\.im|q\.gs|is\.gd|" \
                      r"po\.st|bc\.vc|twitthis\.com|u\.to|j\.mp|buzurl\.com|cutt\.us|u\.bb|yourls\.org|x\.co|" \
                      r"prettylinkpro\.com|scrnch\.me|filoops\.info|vzturl\.com|qr\.net|1url\.com|tweez\.me|v\.gd|" \
                      r"tr\.im|link\.zip\.net"

In [309]:
def tiny_url(url):
    match = re.search(shortening_services,url)
    if match:
        return 1
    else:
        return 0

In [310]:
def prefix_suffix(url):
    if '-' in url:
        return 1            
    else:
        return 0

In [311]:
import re
from bs4 import BeautifulSoup
import whois
import urllib
import urllib.request
from datetime import datetime

In [312]:
def web_traffic(url):
    try:
        rank = BeautifulSoup(urllib.request.urlopen("http://data.alexa.com/data?cli=10&dat=s&url=" + url).read(), "xml").find(
            "REACH")['RANK']
        rank = int(rank)
    except TypeError:
        return 1
    if rank < 100000:
        return 1
    else:
        return 0

In [422]:
def domain_age(domain_name):
    creation_date = domain_name.creation_date
    expiration_date = domain_name.expiration_date
    
    if (isinstance(creation_date, str) or isinstance(expiration_date, str)):
        try:
            creation_date = datetime.strptime(creation_date,'%Y-%m-%d')
            expiration_date = datetime.strptime(expiration_date,"%Y-%m-%d")
        except:
            return 1
    if ((expiration_date is None) or (creation_date is None)):
        return 1
    elif ((type(expiration_date) is list) or (type(creation_date) is list)):
        return 1
    else:
        ageofdomain = abs((expiration_date - creation_date).days)
        if ageofdomain < 100:
            age = 1
        else:
            age = 0
        return age

In [423]:
import requests

In [424]:
def iframe(response):
    if response == "":
        return 1
    else:
        if re.findall(r"[<iframe>|<frameBorder>]", response.text):
            return 0
        else:
            return 1

In [425]:
def mouse_over(response): 
    if response == "" :
        return 1
    else:
        if re.findall("<script>.+onmouseover.+</script>", response.text):
            return 1
        else:
            return 0

In [426]:
def right_click(response):
    if response == "":
        return 1
    else:
        if re.findall(r"event.button ?== ?2", response.text):
            return 0
        else:
            return 1

In [427]:
def forwarding(response):
    if response == "":
        return 1
    else:
        if len(response.history) <= 2:
            return 0
        else:
            return 1

In [428]:
def feature_extraction(url):

    features = []
    
    features.append(if_ip(url))
    features.append(at_sign(url))
    features.append(get_length(url))
    features.append(get_depth(url))
    features.append(if_https_in_domain(url))
    features.append(tiny_url(url))
    features.append(prefix_suffix(url))
    
    dns = 0
    try:
        domain_name = whois.query(urlparse(url).netloc)
    except:
        dns = 1
  
    features.append(dns)
    features.append(web_traffic(url))
    features.append(1 if dns == 1 else domain_age(domain_name))
    
    try:
        response = requests.get(url)
    except:
        response = ""
    features.append(iframe(response))
    features.append(mouse_over(response))
    features.append(right_click(response))
    features.append(forwarding(response))
    
    return features

In [460]:
a = feature_extraction('https://extratorrent.cc')

In [461]:
a

[0, 0, 23, 2, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0]

In [462]:
b = np.array(a).reshape(1, -1)

In [463]:
b

array([[ 0,  0, 23,  2,  0,  0,  0,  0,  0,  0,  1,  0,  1,  0]])

In [464]:
forest.predict(b)

array([1])

In [447]:
precision_score(train_Y, forest.predict(train_X))

0.951862464183381

In [448]:
recall_score(test_Y, forest.predict(test_X))

0.8612670408981555

In [233]:
filename = 'finalized_model.sav'

In [235]:
pickle.dump(forest, open(filename, 'wb'))

In [446]:
result = loaded_model.score(train_X, train_Y)

NameError: name 'loaded_model' is not defined

In [468]:
test_X

,Have_IP,Have_At,URL_Length,URL_Depth,https_Domain,TinyURL,Prefix/Suffix,DNS_Record,Web_Traffic,Domain_Age,iFrame,Mouse_Over,Right_Click,Web_Forwards
8443,0,0,26,0,0,0,0,0,1,0,0,0,1,0
7323,0,0,10,2,0,0,0,0,1,0,0,0,1,0
2967,0,1,22,3,0,1,0,1,1,1,0,0,1,0
5623,0,0,19,5,0,0,0,0,0,0,0,0,1,0
3815,0,0,43,0,0,0,1,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6502,0,0,14,2,0,0,0,0,1,1,0,0,1,0
7191,0,0,12,1,0,0,0,0,1,0,0,0,1,0
3238,0,0,11,1,0,0,0,0,1,1,0,0,1,0
3507,0,0,14,8,0,0,0,0,1,0,0,0,1,0
9098,0,0,8,1,0,0,0,0,0,0,0,0,1,0